version: '3.5'

services:
  db:
    container_name: ecommerce
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5437:5432"
    volumes:
      - ./init/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
